### ISSUE TITLE
code signing certificate

### ISSUE THREAD

**Issue by kubaszostak** [amd989/Symlinker#16]
On TODO section you have "Get a real code signing certificate". What about free certifcate for open source developers?:
https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml

**Comment by amd989** [comment]
Hello,

Sorry for the late response. Thank you for suggesting this! I will gather the required documents and request it.

Regards.

**Comment by McoreD** [comment]
That didn't look free to me? http://i.imgur.com/8Q605fu.png

**Comment by amd989** [comment]
It wasn't free, they started charging at some point in 2015, I missed the boat, I finally got the cert. I will be signing my code with it and releasing a new version.

Thanks!
