### ISSUE TITLE
Downloads link not working

### ISSUE THREAD

**Issue by raykai** [amd989/Symlinker#17]
your Downloads link are not working ....

**Comment by atyachin** [comment]
Same issue here..Can you please post a working binary?
Tx!

**Comment by amd989** [comment]
I just tried and they seem to be working fine.

I created a release in Github to allow you to download the .exe. However running from the .exe means that you wont have auto-update whenever I release a new version.

https://github.com/amd989/Symlinker/releases

Regards!
