### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by prakashslm** [amd989/Symlinker#18]
Hi,
Just want to know is there a way to avoid using cmd. because cmd will required sufficient privilege (administrator).

thank you,

Prakash

**Comment by amd989** [comment]
Hello Prakash,

The main idea of this application was to create a wrapper around the mklink command to avoid using the console itself.

There might be a way of doing it, this app is not that.

Administrator permissions are only required over windows 8 or above, which version of windows are you using?
